const countries = [
  { iso: 'USA', locale: 'global.country.usa', iso2: 'US' },
  { iso: 'POL', locale: 'global.country.pol', iso2: 'PL' },
  { iso: 'NLD', locale: 'global.country.nld', iso2: 'NL' },
  { iso: 'BRA', locale: 'global.country.bra', iso2: 'BR' },
  { iso: 'LVA', locale: 'global.country.lva', iso2: 'LV' },
  { iso: 'FRA', locale: 'global.country.fra', iso2: 'FR' },
  { iso: 'ROU', locale: 'global.country.rou', iso2: 'RO' },
  { iso: 'CAN', locale: 'global.country.can', iso2: 'CA' },
  { iso: 'NOR', locale: 'global.country.nor', iso2: 'NO' },
  { iso: 'AUT', locale: 'global.country.aut', iso2: 'AT' },
  { iso: 'GBR', locale: 'global.country.gbr', iso2: 'GB' },
  { iso: 'UKR', locale: 'global.country.ukr', iso2: 'UA' },
  { iso: 'TUR', locale: 'global.country.tur', iso2: 'TR' },
  { iso: 'JPN', locale: 'global.country.jpn', iso2: 'JP' },
  { iso: 'ISR', locale: 'global.country.isr', iso2: 'IL' },
  { iso: 'TWN', locale: 'global.country.twn', iso2: 'TW' },
  { iso: 'KOR', locale: 'global.country.kor', iso2: 'KR' },
  { iso: 'ESP', locale: 'global.country.esp', iso2: 'ES' },
  { iso: 'DEU', locale: 'global.country.deu', iso2: 'DE' },
  { iso: 'SGP', locale: 'global.country.sgp', iso2: 'SG' },
  { iso: 'HKN', locale: 'global.country.hkn', iso2: 'HK' },
  { iso: 'THA', locale: 'global.country.tha', iso2: 'TH' },
  { iso: 'IND', locale: 'global.country.ind', iso2: 'IN' },
  { iso: 'ITA', locale: 'global.country.ita', iso2: 'IT' },
] as const;

export default countries;
